Repository evolvedbinary/prosemirror-lwdita, pull requests merged in 2024-04, with the labels that each got.

#241 Fix the build
  prosemirror-jdita-demo/package.json
  yarn.lock
Labels: bug, cla-signed

#243 Update from Parcel v1 to Parcel v2
  .gitignore
  prosemirror-jdita-demo/index.html
  prosemirror-jdita-demo/package.json
  prosemirror-jdita-demo/style/style.scss
  yarn.lock
Labels: enhancement, cla-signed

#244 Simplify our tsconfig
  .gitignore
  prosemirror-jdita-demo/tsconfig.json
  prosemirror-jdita/package.json
  prosemirror-jdita/tsconfig.json
  yarn.lock
Labels: enhancement, cla-signed

#225 Unit tests for Prosemirror-Jdita
  prosemirror-jdita/src/commands.ts
  prosemirror-jdita/src/document.spec.ts
  prosemirror-jdita/src/document.ts
  prosemirror-jdita/src/schema.spec.ts
  prosemirror-jdita/src/schema.ts
  prosemirror-jdita/src/tests/commands.spec.ts
  prosemirror-jdita/src/tests/document.spec.ts
  prosemirror-jdita/src/tests/dom.spec.ts
  prosemirror-jdita/src/tests/schema.spec.ts
  prosemirror-jdita/src/tests/test-utils.ts
  prosemirror-jdita/src/tests/tests.ts
  prosemirror-jdita/src/tests/text.spec.ts
  prosemirror-jdita/src/tests/topic.spec.ts
  prosemirror-jdita/src/tests/xml.ts
Labels: cla-signed
