Repository evolvedbinary/prosemirror-lwdita, pull requests merged in 2024-10, with the labels that each got.

#405 Show user notifications for final result after publication
  packages/prosemirror-lwdita-demo/style/style.scss
  packages/prosemirror-lwdita/src/app-config.ts
  packages/prosemirror-lwdita/src/commands.ts
  packages/prosemirror-lwdita/src/github-integration/request.ts
  packages/prosemirror-lwdita/src/github-integration/toast.ts
Labels: cla-signed

#413 GitHub API calls retry on error
  packages/prosemirror-lwdita-backend/src/api/controller/github.controller.ts
  packages/prosemirror-lwdita-backend/src/api/modules/octokit.module.mts
Labels: cla-signed

#416 Improve user UX regarding errors in the editor during file & GitHub operations
  packages/prosemirror-lwdita-demo/error.html
  packages/prosemirror-lwdita-demo/package.json
  packages/prosemirror-lwdita-demo/src/demo-plugin.ts
  packages/prosemirror-lwdita-demo/src/error-handler.ts
  packages/prosemirror-lwdita-demo/src/example.ts
  packages/prosemirror-lwdita-demo/style/style.scss
  packages/prosemirror-lwdita/src/app-config.ts
  packages/prosemirror-lwdita/src/commands.ts
  packages/prosemirror-lwdita/src/github-integration/github.plugin.ts
  packages/prosemirror-lwdita/src/github-integration/request.ts
  packages/prosemirror-lwdita/src/index.ts
  packages/prosemirror-lwdita/src/toast.ts
Labels: cla-signed

#420 Add `eslint` to all TypeScript project files
  .eslintignore
  .eslintrc
  package.json
  packages/prosemirror-lwdita-backend/.eslintrc
  packages/prosemirror-lwdita-backend/package.json
  packages/prosemirror-lwdita-backend/src/api/routes/github.router.ts
  packages/prosemirror-lwdita-backend/src/server.ts
  packages/prosemirror-lwdita-backend/tests/githubRouter.spec.ts
  packages/prosemirror-lwdita-demo/cypress.config.ts
  packages/prosemirror-lwdita-demo/cypress/e2e/welcome-note.cy.ts
  packages/prosemirror-lwdita-demo/cypress/support/commands.ts
  packages/prosemirror-lwdita-demo/cypress/support/e2e.ts
  packages/prosemirror-lwdita-demo/package.json
  packages/prosemirror-lwdita-demo/src/demo-plugin.ts
  packages/prosemirror-lwdita-demo/src/doc.ts
  packages/prosemirror-lwdita/.eslintrc
  packages/prosemirror-lwdita/package.json
  packages/prosemirror-lwdita/src/document.ts
  yarn.lock
Labels: cla-signed

#438 Create configuration files for Client and Server
  packages/prosemirror-lwdita-backend/README.md
  packages/prosemirror-lwdita-backend/package.json
  packages/prosemirror-lwdita-backend/server-config.json
  packages/prosemirror-lwdita-backend/src/api/modules/octokit.module.mts
  packages/prosemirror-lwdita-backend/src/server.ts
  packages/prosemirror-lwdita-backend/tsconfig.json
  packages/prosemirror-lwdita-demo/src/demo-plugin.ts
  packages/prosemirror-lwdita-demo/src/error-handler.ts
  packages/prosemirror-lwdita-demo/src/example.ts
  packages/prosemirror-lwdita/app-config.json
  packages/prosemirror-lwdita/src/app-config.ts
  packages/prosemirror-lwdita/src/commands.ts
  packages/prosemirror-lwdita/src/github-integration/github.plugin.ts
  packages/prosemirror-lwdita/src/github-integration/request.ts
  packages/prosemirror-lwdita/src/index.ts
  packages/prosemirror-lwdita/src/toast.ts
  packages/prosemirror-lwdita/tests/github.plugin.spec.ts
  packages/prosemirror-lwdita/tests/request.spec.ts
  tsconfig.json
  yarn.lock
Labels: cla-signed

#429 Redirect the user to petalBot install Page
  packages/prosemirror-lwdita-backend/package.json
  packages/prosemirror-lwdita-backend/src/api/controller/github.controller.ts
  packages/prosemirror-lwdita-backend/src/api/modules/octokit.module.mts
  packages/prosemirror-lwdita-demo/cypress/e2e/github-inegration.cy.ts
  packages/prosemirror-lwdita/src/github-integration/github.plugin.ts
  packages/prosemirror-lwdita/src/github-integration/request.ts
Labels: cla-signed

#439 How to deploy on production
  packages/prosemirror-lwdita-backend/README.md
  packages/prosemirror-lwdita-demo/README.md
Labels: cla-signed

#463 Cleanup the config for prosemirror-lwdita-backend
  packages/prosemirror-lwdita-backend/.env.example
  packages/prosemirror-lwdita-backend/README.md
  packages/prosemirror-lwdita-backend/config.json
  packages/prosemirror-lwdita-backend/package.json
  packages/prosemirror-lwdita-backend/server-config.json
  packages/prosemirror-lwdita-backend/src/api/controller/github.controller.ts
  packages/prosemirror-lwdita-backend/src/api/modules/octokit.module.mts
  packages/prosemirror-lwdita-backend/src/api/routes/github.router.ts
  packages/prosemirror-lwdita-backend/src/config.ts
  packages/prosemirror-lwdita-backend/src/server.ts
  packages/prosemirror-lwdita-backend/tests/github.controller.spec.ts
  packages/prosemirror-lwdita-backend/tests/githubRouter.spec.ts
  packages/prosemirror-lwdita-backend/tests/mock.config.ts
  packages/prosemirror-lwdita-backend/tests/mock.github.controller.ts
  yarn.lock
Labels: enhancement, cla-signed

#464 Update to LwDITA 3.1.0
  packages/prosemirror-lwdita-demo/cypress/e2e/download.cy.ts
  packages/prosemirror-lwdita-demo/package.json
  packages/prosemirror-lwdita-demo/src/demo-plugin.ts
  packages/prosemirror-lwdita/package.json
  packages/prosemirror-lwdita/src/schema.ts
  yarn.lock
Labels: enhancement, cla-signed

#466 Update the raw link api
  packages/prosemirror-lwdita/src/github-integration/github.plugin.ts
  packages/prosemirror-lwdita/tests/github.plugin.spec.ts
Labels: cla-signed

#467 Add DITA MIME type and allow `.dita` files to be uploaded to the editor
  packages/prosemirror-lwdita-demo/src/demo-plugin.ts
Labels: cla-signed

#471 Fix the config loading process and add the new demo script entry function
  packages/prosemirror-lwdita-demo/.parcelrc
  packages/prosemirror-lwdita-demo/README.md
  packages/prosemirror-lwdita-demo/package.json
  packages/prosemirror-lwdita-demo/src/example.ts
  packages/prosemirror-lwdita/src/github-integration/request.ts
  yarn.lock
Labels: cla-signed

#478 Copy the whole dist folder
  packages/prosemirror-lwdita-backend/README.md
Labels: cla-signed

#485 Fix the path to the files to deploy for the backend
  packages/prosemirror-lwdita-backend/README.md
Labels: bug, cla-signed
